### ISSUE TITLE
Adding instructions produces a weird display

### ISSUE THREAD

**Issue by stuartcusackie** [eminos/statamic-tabs#1]
I just tried adding instructions to a tab and got this:
![image](https://github.com/eminos/statamic-tabs/assets/20210934/0922f6a7-1000-4294-9b20-1fc34885df75)

The 'Test' instruction appears no matter what tab is selected.

Thanks and nice package! I wish it was part of the core!

**Comment by eminos** [comment]
Thank for reporting this. I've fixed it in v1.0.1.
